var TABLE_PREFIX = 'dotmuncher_';

var POSITION_EVENT = 1,
	OHHAI_EVENT = 2,
	PHONE_EATEN_EVENT = 6,
	ITEM_EATEN_EVENT = 7,
	GAME_OVER = 8;

var TYPENUM_TYPENAM_MAP = {
    POSITION_EVENT: 'POSITION_EVENT',
    OHHAI_EVENT: 'OHHAI_EVENT',
};
	
